name: Testing

on:
  push:
    branches-ignore:
      - main

  pull_request:
    branches:
      - main

jobs:
  unit_testing:
    uses: ./.github/workflows/Unit_testing.yml

  e2e-testing:
    uses: ./.github/workflows/E2e_testing.yml
